### ISSUE TITLE
argument -e -batch-size 

### ISSUE THREAD

**Issue by Henriquekc** [badoo/parallel_cucumber#48]
Hi, I have just read the documentation and I'm trying to run more than 1 test with 1 worker

I'm trying to run like this with no sucess: 

```
parallel_cucumber -e --batch-size 3 features/
```
 
Log above:

```
Traceback (most recent call last):
        4: from C:/Ruby25-x64/bin/parallel_cucumber:23:in `<main>'
        3: from C:/Ruby25-x64/bin/parallel_cucumber:23:in `load'
        2: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/parallel_tests-2.31.0/bin/parallel_cucumber:9:in `<top (required)>'
        1: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/parallel_tests-2.31.0/lib/parallel_tests/cli.rb:12:in `run'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/parallel_tests-2.31.0/lib/parallel_tests/cli.rb:229:in `parse_options!': invalid option: --batch-size (OptionParser::InvalidOption)
```

What am I doing wrong?

**Comment by sleekweasel** [comment]
Option -e needs an argument

**Comment by Henriquekc** [comment]
Sorry, I'm really new, could you give me an example how to use please?

**Comment by rajdeepv** [comment]
@Henriquekc have a look here https://github.com/rajdeepv/cucumber_example/blob/628078ee1351aa76ce9a64083fbc5e3be721d1da/rakefile#L33
